language: objective-c

osx_image: xcode8.3

script:
  - xcodebuild -version
  - xcodebuild -workspace CI-Template.xcworkspace -scheme 'CI-Template' -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" test